[package]
name = "table-driven-lexer"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0"
thiserror = "2.0"
miette = "7.6"
tower-lsp = "0.20"

[dev-dependencies]
quickcheck = "1"
serde_json = "1.0"
serde = "1"
